---
driver:
  name: docker

provisioner:
  name: chef_zero
  data_bags_path: 'test/integration/data_bags'

platforms:
  - name: ubuntu-14.04
    driver_config:
      privileged: true

suites:
  - name: base
    run_list: [
      'recipe[rubygems-people]'
    ]
  - name: balancer
    run_list: [
      'recipe[rubygems-balancer]'
    ]
    attributes:
      dev_mode: true
  - name: database
    run_list: []
  - name: application
    run_list: []
