---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bag_path: 'test/integration/data_bags'

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: base
    run_list:
    attributes:
  - name: balancer
    run_list: ['recipe[rubygems-balancer]']
    attributes:
      dev_mode: true
