---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: base
    run_list:
    attributes:
  - name: balancer
    run_list: ['recipe[rubygems-balancer]']
    attributes:
