AllCops:
  Exclude:
    - vendor/**/*
    - /**/files/**/*

Encoding:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
NumericLiterals:
  Enabled: false
LineLength:
  Enabled: false
Style/WordArray:
  MinSize: 2
