AllCops:
  Exclude:
    - vendor/**/*
    - /**/files/**/*
    - cookbooks/rubygems-chef/templates/default/librato.rb

Encoding:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
NumericLiterals:
  Enabled: false
LineLength:
  Enabled: false
Style/WordArray:
  MinSize: 2
Style/RescueModifier:
  Enabled: false
